resources:
    Carcel\User\Domain\Model\Write\User:
        collectionOperations:
#            get:
#                controller: 'ApiPlatform\Core\Action\NotFoundAction'
#                read': false,
#                status: 404
            post:
                input: 'Carcel\User\Application\Command\CreateUser'
                messenger: input
                output: false
                status: 202
        itemOperations:
            delete:
                input: 'Carcel\User\Application\Command\DeleteUser'
                messenger: input
                output: false
                status: 202
#            get:
#                controller: 'ApiPlatform\Core\Action\NotFoundAction'
#                read': false,
#                status: 404
            put:
                input: 'Carcel\User\Application\Command\UpdateUser'
                messenger: input
                output: false
                status: 202

    Carcel\User\Application\Query\GetUserCollection:
        collectionOperations:
            get:
                path: '/users'
        itemOperations: {}

    Carcel\User\Application\Query\GetUser:
        collectionOperations: {}
        itemOperations:
            get:
                path: '/users/{id}'
        properties:
            identifier:
                identifier: true
